name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install setuptools
      run: pip install setuptools
        
    - name: Get version
      id: get-version
      run: |
        echo "VERSION=v$(python3 setup.py --version)" >> $GITHUB_ENV

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.GITHUBAWSIPENUMACCESSTOKEN }}     

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: | 
          momelod/awsipenum:${{ env.VERSION }}
          momelod/awsipenum:latest

    - name: Check if tag already exists
      uses: mukunku/tag-exists-action@v1.0.0
      id: check_tag
      with:
        tag: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GHTOKEN }}

    - name: Create and push tag
      if: ${{ steps.check_tag.outputs.exists == 'false' }}
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        tagging_message: ${{ env.VERSION }}
        skip_dirty_check: true
