name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install setuptools
      run: pip install setuptools
        
    - name: Get version
      run: 
        echo "::set-output name=VERSION::v$(python3 setup.py --version)"
          
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag momelod/awsipenum:${{ steps.version.outputs.VERSION }}
