name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    
    - name: Update PATH
      run: echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install setuptools
      run: pip install setuptools
        
    - name: Get version
      id: get-version
      run: |
        echo "VERSION=v$(python3 setup.py --version) >> $GITHUB_OUTPUT"
          
    - name: Build the Docker image
      run: |
        source "$GITHUB_OUTPUT"
        echo "Version is $VERSION"
        docker build . --file Dockerfile --tag momelod/awsipenum:${{ steps.get-version.outputs.VERSION }}
